name: Build and Release CLI

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # JOB 1: Create version tag (ONLY ONCE)
  version:
    runs-on: ubuntu-latest
    outputs:
      new_tag: ${{ steps.tagger.outputs.new_tag }}

    steps:
      - uses: actions/checkout@v4

      - name: Bump version
        id: tagger
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: patch # v1.0.3 -> v1.0.4

  # JOB 2: Build for all OS
  build:
    needs: version

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt -r requirements-build.txt

      - name: Build
        run: pyinstaller --onefile --name unify --clean main.py

      # rename files so they don't overwrite each other
      - name: Rename output
        run: |
          if [ "$RUNNER_OS" = "Windows" ]; then
            mv dist/unify.exe dist/unify-windows.exe
          elif [ "$RUNNER_OS" = "macOS" ]; then
            mv dist/unify dist/unify-macos
          else
            mv dist/unify dist/unify-linux
          fi
        shell: bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: dist/*

  # JOB 3: Create release (ONLY ONCE)
  release:
    needs: [version, build]

    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ needs.version.outputs.new_tag }}
          files: |
            **/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
